name: Scala CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - run: sbt clean
    - run: sbt coverage
    - name: Run tests
      run: sbt clean
    - name: Generate coverage report
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: actions/upload-artifact@v3
      with:
         name: scoverage-report
         path: target/scala-3.2.0/

