name: Scala CI

on:
  push:

permissions:
  contents: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt clean
      - name: Run tests
        run: sbt coverage test
      - name: Generate coverage report
        run: sbt coverageReport
#      - name: Generate documentation
#        run: sbt doc
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Scala Tests
          path: target/test-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Upload coverage to GitHubPage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/scala-3.2.0/scoverage-report # The folder the action should deploy.
          branch: coverage-deploy # The branch the action should deploy to.
#      - name: Upload documentation
#        uses: actions/upload-artifact@v3
#        with:
#          name: documentation
#          path: target/scala-3.2.0/api/

